#!/usr/bin/env python3
"""
    doc
"""

import asyncio
from typing import List

task_wait_random = __import__('3-tasks').task_wait_random


async def task_wait_n(n: int, max_delay: int) -> List[float]:
    """
        Asynchronous routine generated by tasks task_wait_random(max delay)
        and returns an ordered list of delays.

        Args:
            n (int): The number of tasks to spawn.
            max_delay (int): The maximum delay for each task.

        Returns:
            List[float]: A sorted list of delay times.
    """

    tasks = [task_wait_random(max_delay) for _ in range(n)]
    delays = await asyncio.gather(*tasks)

    return sorted(delays)
